--url = 's3://snowflakeparquetdemo'
CREATE OR REPLACE DATABASE PARQUET_DB;
USE DATABASE PARQUET_DB;
CREATE SCHEMA PARQUET_DB.PUBLIC;
CREATE OR REPLACE TABLE PARQUET_DB.PUBLIC.ORDERS_V10 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

--1 Create parquet file format
CREATE OR REPLACE FILE FORMAT PARQUET_DB.PUBLIC.PARQUET_FORMAT TYPE = 'PARQUET';

--2 Create stage pointing to S3 with parquet format
CREATE OR REPLACE STAGE PARQUET_DB.PUBLIC.PARQUET_STAGE
    URL = 's3://snowflakeparquetdemo'
    FILE_FORMAT = (TYPE = 'PARQUET');

--3 List files in stage
LIST @PARQUET_DB.PUBLIC.PARQUET_STAGE;
--4 Create table matching parquet schema
CREATE OR REPLACE TABLE PARQUET_DB.PUBLIC.ORDERS_PARQUET (
    INDEX_LEVEL NUMBER,
    CAT_ID VARCHAR,
    D NUMBER,
    SALE_DATE TIMESTAMP,
    DEPT_ID VARCHAR,
    ID VARCHAR,
    ITEM_ID VARCHAR,
    STATE_ID VARCHAR,
    STORE_ID VARCHAR,
    VALUE NUMBER
);

SELECT * FROM PARQUET_DB.PUBLIC.ORDERS_PARQUET;

COPY INTO PARQUET_DB.PUBLIC.ORDERS_PARQUET
FROM @PARQUET_DB.PUBLIC.PARQUET_STAGE;


