--url = 's3://snowflakeparquetdemo'
CREATE OR REPLACE DATABASE PARQUET_DB;
USE DATABASE PARQUET_DB;
CREATE SCHEMA PARQUET_DB.PUBLIC;
CREATE OR REPLACE TABLE PARQUET_DB.PUBLIC.ORDERS_V10 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));

--1 Create parquet file format
CREATE OR REPLACE FILE FORMAT PARQUET_DB.PUBLIC.PARQUET_FORMAT TYPE = 'PARQUET';

--2 Create stage pointing to S3 with parquet format
CREATE OR REPLACE STAGE PARQUET_DB.PUBLIC.PARQUET_STAGE
    URL = 's3://snowflakeparquetdemo'
    FILE_FORMAT = PARQUET_DB.PUBLIC.PARQUET_FORMAT;

--3 List files in stage
LIST @PARQUET_DB.PUBLIC.PARQUET_STAGE;
--4 Create table matching parquet schema
CREATE OR REPLACE TABLE PARQUET_DB.PUBLIC.ORDERS_PARQUET (
    INDEX_LEVEL NUMBER,
    CAT_ID VARCHAR,
    D NUMBER,
    SALE_DATE TIMESTAMP,
    DEPT_ID VARCHAR,
    ID VARCHAR,
    ITEM_ID VARCHAR,
    STATE_ID VARCHAR,
    STORE_ID VARCHAR,
    VALUE NUMBER
);

--5 Load parquet data using COPY INTO
COPY INTO PARQUET_DB.PUBLIC.ORDERS_PARQUET
FROM (
    SELECT
        $1:__index_level_0__::NUMBER,
        $1:cat_id::VARCHAR,
        $1:d::NUMBER,
        TO_TIMESTAMP($1:date::NUMBER, 6),
        $1:dept_id::VARCHAR,
        $1:id::VARCHAR,
        $1:item_id::VARCHAR,
        $1:state_id::VARCHAR,
        $1:store_id::VARCHAR,
        $1:value::NUMBER
    FROM @PARQUET_DB.PUBLIC.PARQUET_STAGE
);

--6 Row count
SELECT COUNT(*) AS ROW_COUNT FROM PARQUET_DB.PUBLIC.ORDERS_PARQUET;



