CREATE DATABASE OM_DEV;

CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;


CREATE OR REPLACE STAGE OM_DEV.BRONZE.EMPLOYEE_STAGE
STORAGE_INTEGRATION = S3_INT
URL = 's3://joshna-snow-20/csv/'
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

DESC STAGE OM_DEV.BRONZE.EMPLOYEE_STAGE;

LIST @OM_DEV.BRONZE.EMPLOYEE_STAGE;

CREATE OR REPLACE TABLE OM_DEV.BRONZE.EMPLOYEES (
  show_id STRING,
  type STRING,
  title STRING,
  director STRING,
  cast STRING,
  country STRING,
  date_added STRING,
  release_year STRING,
  rating STRING,
  duration STRING,
  listed_in STRING,
  description STRING
);

COPY INTO OM_DEV.BRONZE.EMPLOYEES
FROM @OM_DEV.BRONZE.EMPLOYEE_STAGE
FILES = ('netflix_titles.csv')
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
FORCE=TRUE;

TRUNCATE TABLE OM_DEV.BRONZE.EMPLOYEES;

CREATE TRANSIENT TABLE OM_DEV.BRONZE.EMPLOYEES_V0 (
  id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  city STRING,
  department STRING
);

CREATE TEMPORARY TABLE OM_DEV.BRONZE.EMPLOYEES_TEMP (
  id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  city STRING,
  department STRING
);

CREATE OR REPLACE DYNAMIC TABLE OM_DEV.BRONZE.EMPLOYEES_DT
  TARGET_LAG = '1 hour'
  WAREHOUSE = COMPUTE_WH
AS
  SELECT * FROM OM_DEV.BRONZE.EMPLOYEES;

CREATE OR REPLACE EXTERNAL TABLE OM_DEV.BRONZE.EMPLOYEES_EXT (
  show_id STRING AS (VALUE:c1::STRING),
  type STRING AS (VALUE:c2::STRING),
  title STRING AS (VALUE:c3::STRING),
  director STRING AS (VALUE:c4::STRING),
  cast STRING AS (VALUE:c5::STRING),
  country STRING AS (VALUE:c6::STRING),
  date_added STRING AS (VALUE:c7::STRING),
  release_year STRING AS (VALUE:c8::STRING),
  rating STRING AS (VALUE:c9::STRING),
  duration STRING AS (VALUE:c10::STRING),
  listed_in STRING AS (VALUE:c11::STRING),
  description STRING AS (VALUE:c12::STRING)
)
LOCATION = @OM_DEV.BRONZE.EMPLOYEE_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
AUTO_REFRESH = FALSE;

  


SHOW TABLES IN SCHEMA OM_DEV.BRONZE;;

SELECT COUNT(*) 
FROM OM_DEV.BRONZE.EMPLOYEES;

SELECT * FROM OM_DEV.BRONZE.EMPLOYEES;

 SELECT * FROM OM_DEV.BRONZE.EMPLOYEES_V0;

  SELECT * FROM OM_DEV.BRONZE.EMPLOYEES_TEMP;
  SELECT * FROM OM_DEV.BRONZE.EMPLOYEES_EXT;