--s3 url --- s3://bucketsnowflakes3/OrderDetails.csv
  ---ddl
  CREATE DATABASE OUR_FIRST_DB;
  USE DATABASE OUR_FIRST_DB;
  CREATE SCHEMA OUR_FIRST_DB.PUBLIC;
  CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));
	 CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));
    COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS 
   FROM 's3://bucketsnowflakes3/OrderDetails.csv'
   FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1)
   SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS;

SELECT ORDER_ID,
    CASE WHEN PROFIT >= 0 THEN PROFIT END AS POSITIVE_PROFIT,
    CASE WHEN PROFIT < 0 THEN PROFIT END AS NEGATIVE_PROFIT
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

SELECT ORDER_ID,
    SUM(CASE WHEN PROFIT >= 0 THEN PROFIT ELSE 0 END) AS TOTAL_POSITIVE_PROFIT,
    SUM(CASE WHEN PROFIT < 0 THEN PROFIT ELSE 0 END) AS TOTAL_NEGATIVE_PROFIT
FROM OUR_FIRST_DB.PUBLIC.ORDERS
GROUP BY ORDER_ID
ORDER BY ORDER_ID;

-- Window Functions on ORDERS table

-- ROW_NUMBER, RANK, DENSE_RANK by profit within each category
SELECT ORDER_ID, CATEGORY, PROFIT,
    ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS ROW_NUM,
    RANK() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS RANK_VAL,
    DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS DENSE_RANK_VAL
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

-- Running total of amount and average profit per category
SELECT ORDER_ID, CATEGORY, AMOUNT, PROFIT,
    SUM(AMOUNT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS RUNNING_TOTAL_AMOUNT,
    AVG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS RUNNING_AVG_PROFIT
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

-- LEAD and LAG to compare profit with next/previous order in same category
SELECT ORDER_ID, CATEGORY, PROFIT,
    LAG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS PREV_PROFIT,
    LEAD(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS NEXT_PROFIT,
    PROFIT - LAG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS PROFIT_CHANGE
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

-- FIRST_VALUE and LAST_VALUE per category
SELECT ORDER_ID, CATEGORY, PROFIT,
    FIRST_VALUE(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS MAX_PROFIT_IN_CATEGORY,
    LAST_VALUE(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS MIN_PROFIT_IN_CATEGORY
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

-- NTILE to divide orders into quartiles by amount
SELECT ORDER_ID, CATEGORY, AMOUNT,
    NTILE(4) OVER (ORDER BY AMOUNT DESC) AS QUARTILE
FROM OUR_FIRST_DB.PUBLIC.ORDERS;

-- 5 Window Functions using CTEs

-- 1. ROW_NUMBER, RANK, DENSE_RANK using CTE
WITH ranked_orders AS (
    SELECT ORDER_ID, CATEGORY, PROFIT,
        ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS ROW_NUM,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS RANK_VAL,
        DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS DENSE_RANK_VAL
    FROM OUR_FIRST_DB.PUBLIC.ORDERS
)
SELECT * FROM ranked_orders;

-- 2. Running total and average using CTE
WITH running_totals AS (
    SELECT ORDER_ID, CATEGORY, AMOUNT, PROFIT,
        SUM(AMOUNT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS RUNNING_TOTAL_AMOUNT,
        AVG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS RUNNING_AVG_PROFIT
    FROM OUR_FIRST_DB.PUBLIC.ORDERS
)
SELECT * FROM running_totals;

-- 3. LAG and LEAD using CTE
WITH lag_lead_orders AS (
    SELECT ORDER_ID, CATEGORY, PROFIT,
        LAG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS PREV_PROFIT,
        LEAD(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS NEXT_PROFIT,
        PROFIT - LAG(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY ORDER_ID) AS PROFIT_CHANGE
    FROM OUR_FIRST_DB.PUBLIC.ORDERS
)
SELECT * FROM lag_lead_orders;

-- 4. FIRST_VALUE and LAST_VALUE using CTE
WITH first_last_profit AS (
    SELECT ORDER_ID, CATEGORY, PROFIT,
        FIRST_VALUE(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC) AS MAX_PROFIT_IN_CATEGORY,
        LAST_VALUE(PROFIT) OVER (PARTITION BY CATEGORY ORDER BY PROFIT DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS MIN_PROFIT_IN_CATEGORY
    FROM OUR_FIRST_DB.PUBLIC.ORDERS
)
SELECT * FROM first_last_profit;

-- 5. NTILE using CTE
WITH quartile_orders AS (
    SELECT ORDER_ID, CATEGORY, AMOUNT,
        NTILE(4) OVER (ORDER BY AMOUNT DESC) AS QUARTILE
    FROM OUR_FIRST_DB.PUBLIC.ORDERS
)
SELECT * FROM quartile_orders;
