
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID 
INT,FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,EMAIL VARCHAR,PHONE_NUMBER VARCHAR,HIRE_DATE DATE,JOB_ID VARCHAR,SALARY NUMBER,MANAGER_ID INT,DEPARTMENT_ID INT);
CREATE DATABASE IF NOT EXISTS HR;
CREATE SCHEMA TCS;
DROP DATABASE HR;
DROP DATABASE EMPLOYEES;

