CREATE or replace TABLE OMS_DEV.BRONZE.CUSTOMER_10 (
    CID INT,
    CNAME VARCHAR(10),
    ADDRESS VARCHAR(10)
);

INSERT INTO OMS_DEV.BRONZE.CUSTOMER_10 (CID, CNAME, ADDRESS) VALUES
--(11, 'Alice', 'New York'),
--(2, 'Bob', 'Chicago'),
--(3, 'Charlie', 'Dallas'),
(4, 'Diana', 'Seattle'),
(5, 'Eve', 'Boston');


update OMS_DEV.BRONZE.CUSTOMER_10
          set ADDRESS = 'blr'
    where cid = 4 ;
   
delete from OMS_DEV.BRONZE.CUSTOMER_10 where cid = 11;

select * from  OMS_DEV.BRONZE.CUSTOMER_10 ;

delete from   OMS_DEV.BRONZE.CUSTOMER_10;


CREATE or replace TABLE OMS_DEV.silver.CUSTOMER_tgt  clone
OMS_DEV.BRONZE.CUSTOMER_10 ;
---------------------

CREATE or replace TABLE OMS_DEV.silver.CUSTOMER_tgt (
    CID INT,
    CNAME VARCHAR(10),
    ADDRESS VARCHAR(10)
);



select * from  OMS_DEV.silver.CUSTOMER_tgt  ;



-------------------------------
create or replace stream OMS_DEV.BRONZE.CUSTOMER_stream on table OMS_DEV.BRONZE.CUSTOMER_10 ;

select * from OMS_DEV.BRONZE.CUSTOMER_stream;


MERGE INTO OMS_DEV.SILVER.CUSTOMER_TGT AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_STREAM
) AS src
ON tgt.CID = src.CID
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    DELETE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.CNAME = src.CNAME, tgt.ADDRESS = src.ADDRESS
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS) VALUES (src.CID, src.CNAME, src.ADDRESS);



create or replace task OMS_DEV.BRONZE.CUSTOMER_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('OMS_DEV.BRONZE.CUSTOMER_STREAM')
AS
MERGE INTO OMS_DEV.SILVER.CUSTOMER_TGT AS tgt
USING (
    SELECT CID, CNAME, ADDRESS, METADATA$ACTION, METADATA$ISUPDATE
    FROM OMS_DEV.BRONZE.CUSTOMER_STREAM
) AS src
ON tgt.CID = src.CID
WHEN MATCHED AND src.METADATA$ACTION = 'DELETE' AND src.METADATA$ISUPDATE = FALSE THEN
    DELETE
WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE THEN
    UPDATE SET tgt.CNAME = src.CNAME, tgt.ADDRESS = src.ADDRESS
WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN
    INSERT (CID, CNAME, ADDRESS) VALUES (src.CID, src.CNAME, src.ADDRESS);



show tasks;

ALTER TASK OMS_DEV.BRONZE.CUSTOMER_TASK RESUME;

ALTER TASK OMS_DEV.BRONZE.CUSTOMER_TASK SUSPEND;


create or replace task OMS_DEV.BRONZE.emp_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0/30 * * * * UTC'
as
delete from employee where status = 'inactive' ;
