CREATE DATABASE  OMS_DEV ;

CREATE SCHEMA BRONZE ;

CREATE SCHEMA SILVER ;

CREATE SCHEMA GOLD ;










CREATE STAGE OMS_DEV.PUBLIC.ORDERS_STAGE
URL = 's3://bucketsnowflakes3'
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1) ;


LIST @OMS_DEV.PUBLIC.ORDERS_STAGE ;



COPY INTO  OMS_DEV.BRONZE.ORDERS
FROM @OUR_FIRST_DB.PUBLIC.ORDERS_STAGE
FILES =('OrderDetails.csv')
force=true ;



  CREATE OR REPLACE TABLE OMS_DEV.BRONZE.ORDERS (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));



    CREATE TRANSIENT TABLE OMS_DEV.BRONZE.ORDERS_V1 (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));


      CREATE TEMPORARY  TABLE OMS_DEV.BRONZE.ORDERS_TEMP (
    ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    QUANTITY INT,
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(30));


    SHOW TABLES;


    SELECT * FROM OMS_DEV.BRONZE.ORDERS;

       SELECT * FROM OMS_DEV.BRONZE.ORDERS_V1;

          SELECT * FROM OMS_DEV.BRONZE.ORDERS_TEMP;



     SELECT * FROM OMS_DEV.BRONZE.ORDERS


     SELECT CATEGORY ,
         SUM (QUANTITY)  
         FROM OMS_DEV.BRONZE.ORDERS
         GROUP BY CATEGORY ;



         


CREATE TEMPORARY TABLE   OMS_DEV.BRONZE.ORDER_AGG AS
(
SELECT CATEGORY ,
         SUM (QUANTITY)  AS TOTAL
         FROM OMS_DEV.BRONZE.ORDERS
         GROUP BY CATEGORY

) ;

SELECT * FROM OMS_DEV.BRONZE.ORDER_AGG;


CREATE OR REPLACE EXTERNAL TABLE OMS_DEV.BRONZE.ORDERS_EXT (
    ORDER_ID VARCHAR(30) AS (VALUE:c1::VARCHAR(30)),
    AMOUNT INT AS (VALUE:c2::INT),
    PROFIT INT AS (VALUE:c3::INT),
    QUANTITY INT AS (VALUE:c4::INT),
    CATEGORY VARCHAR(30) AS (VALUE:c5::VARCHAR(30)),
    SUBCATEGORY VARCHAR(30) AS (VALUE:c6::VARCHAR(30))
)
WITH LOCATION = @OMS_DEV.PUBLIC.ORDERS_STAGE
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1)
PATTERN = '.*OrderDetails.csv';


select * from OMS_DEV.BRONZE.ORDERS_EXT;


---source  -- target


select * from OMS_DEV.BRONZE.ORDERS;

delete from OMS_DEV.BRONZE.ORDERS  where quantity < 10 ;

 SELECT CATEGORY ,
         SUM (QUANTITY)  
         FROM OMS_DEV.BRONZE.ORDERS
         GROUP BY CATEGORY ;


         ---1154  3516  945

create table oms_dev.silver.orders_final
as
(
SELECT CATEGORY ,
         SUM (QUANTITY)  as total
         FROM OMS_DEV.BRONZE.ORDERS
         GROUP BY CATEGORY
)
;

select * from oms_dev.silver.orders_final ;


CREATE OR REPLACE DYNAMIC TABLE OMS_DEV.SILVER.ORDERS__dy_FINAL
    TARGET_LAG = '1 minutes'
    WAREHOUSE = COMPUTE_WH
    AS
    SELECT CATEGORY,
           SUM(QUANTITY) AS TOTAL
    FROM OMS_DEV.BRONZE.ORDERS
    GROUP BY CATEGORY;


    select * from OMS_DEV.SILVER.ORDERS__dy_FINAL ;
