CREATE OR REPLACE TABLE OMS_DEV.BRONZE.CUSTOMERS (
    CID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CNAME VARCHAR,
    AMOUNT NUMBER,
    ADDRESS VARCHAR,
    PHONE VARCHAR,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO OMS_DEV.BRONZE.CUSTOMERS (CNAME, AMOUNT, ADDRESS, PHONE) VALUES
('Rahul', 50000, 'BLR', '9876543210'),
('Priya', 30000, 'HYD', '9123456789'),
('Amit', 45000, 'BLR', '9988776655'),
('Sneha', 60000, 'MUM', '8877665544'),
('Kiran', 25000, 'CHN', '7766554433');

-- 1) Procedure to insert values
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.INSERT_CUSTOMER(
    P_CNAME VARCHAR,
    P_AMOUNT NUMBER,
    P_ADDRESS VARCHAR,
    P_PHONE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO OMS_DEV.BRONZE.CUSTOMERS (CNAME, AMOUNT, ADDRESS, PHONE)
    VALUES (:P_CNAME, :P_AMOUNT, :P_ADDRESS, :P_PHONE);
    RETURN 'Customer inserted successfully';
END;
$$;

CALL OMS_DEV.BRONZE.INSERT_CUSTOMER('Ravi', 40000, 'BLR', '9900112233');

-- 2) Procedure for withdraw logic
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.WITHDRAW(
    P_CID NUMBER,
    P_AMOUNT NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    V_BALANCE NUMBER;
BEGIN
    SELECT AMOUNT INTO :V_BALANCE FROM OMS_DEV.BRONZE.CUSTOMERS WHERE CID = :P_CID;

    IF (:V_BALANCE < :P_AMOUNT) THEN
        RETURN 'Insufficient balance. Current balance: ' || :V_BALANCE;
    END IF;

    UPDATE OMS_DEV.BRONZE.CUSTOMERS
    SET AMOUNT = AMOUNT - :P_AMOUNT,
        UPDATE_TIME = CURRENT_TIMESTAMP()
    WHERE CID = :P_CID;

    RETURN 'Withdrawal successful. New balance: ' || (:V_BALANCE - :P_AMOUNT);
END;
$$;

CALL OMS_DEV.BRONZE.WITHDRAW(1, 1000);

-- 3) Procedure for deposit logic
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.DEPOSIT(
    P_CID NUMBER,
    P_AMOUNT NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    V_BALANCE NUMBER;
BEGIN
    UPDATE OMS_DEV.BRONZE.CUSTOMERS
    SET AMOUNT = AMOUNT + :P_AMOUNT,
        UPDATE_TIME = CURRENT_TIMESTAMP()
    WHERE CID = :P_CID;

    SELECT AMOUNT INTO :V_BALANCE FROM OMS_DEV.BRONZE.CUSTOMERS WHERE CID = :P_CID;

    RETURN 'Deposit successful. New balance: ' || :V_BALANCE;
END;
$$;

CALL OMS_DEV.BRONZE.DEPOSIT(1, 1000);

-- 4) Procedure to display customers based on branch/address
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.GET_CUSTOMERS_BY_ADDRESS(
    P_ADDRESS VARCHAR
)
RETURNS TABLE(CID NUMBER, CNAME VARCHAR, AMOUNT NUMBER, ADDRESS VARCHAR, PHONE VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    RES RESULTSET;
BEGIN
    RES := (SELECT CID, CNAME, AMOUNT, ADDRESS, PHONE
            FROM OMS_DEV.BRONZE.CUSTOMERS
            WHERE UPPER(ADDRESS) = UPPER(:P_ADDRESS));
    RETURN TABLE(RES);
END;
$$;

CALL OMS_DEV.BRONZE.GET_CUSTOMERS_BY_ADDRESS('BLR');

-- 5) Procedure to delete inactive customer
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.DELETE_CUSTOMER(
    P_CID NUMBER
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    DELETE FROM OMS_DEV.BRONZE.CUSTOMERS WHERE CID = :P_CID;
    RETURN 'Customer with CID ' || :P_CID || ' deleted successfully';
END;
$$;

CALL OMS_DEV.BRONZE.DELETE_CUSTOMER(2);

-- 6) Procedure to get mini statement
CREATE OR REPLACE PROCEDURE OMS_DEV.BRONZE.MINI_STATEMENT(
    P_CID NUMBER
)
RETURNS TABLE(CID NUMBER, CNAME VARCHAR, AMOUNT NUMBER, ADDRESS VARCHAR, PHONE VARCHAR, CREATE_TIME TIMESTAMP, UPDATE_TIME TIMESTAMP)
LANGUAGE SQL
AS
$$
DECLARE
    RES RESULTSET;
BEGIN
    RES := (SELECT CID, CNAME, AMOUNT, ADDRESS, PHONE, CREATE_TIME, UPDATE_TIME
            FROM OMS_DEV.BRONZE.CUSTOMERS
            WHERE CID = :P_CID);
    RETURN TABLE(RES);
END;
$$;

CALL OMS_DEV.BRONZE.MINI_STATEMENT(1);



